# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='organizers', verbose_name='Naamakuva'),
        ),
    ]
