# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-06 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracommon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='day',
            field=models.CharField(default='vkl', max_length=3),
        ),
    ]
