# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20160511_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_image',
            field=models.FileField(blank=True, upload_to='headers'),
        ),
    ]
