# Generated by Django 3.1.3 on 2020-11-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_page_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='header_image',
            field=models.FileField(blank=True, help_text='Näytetään sivun ylälaidassa, jos käytettävä teema tukee tätä. Mikäli otsikkokuvaa ei ole asetettu, käytetään yläsivun otsikkokuvaa.', upload_to='headers', verbose_name='Otsikkokuva'),
        ),
    ]
